{
 "title": "Library API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{\"increase(http_requests_received_total{code=~\"5..\"}[5m])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{\"rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{\"rate(http_requests_received_total[1m])\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}